### ISSUE TITLE
Links to github missing

### ISSUE THREAD

**Issue by dennyac** [AzureCosmosDB/CosmicNotes#1]
Hi @rimman, these notes are great! Can you let me know the Github link mentioned in this slide - https://azurecosmosdb.github.io/CosmicNotes/images/36.png

**Comment by rimman** [comment]
Thank you. Here it is https://github.com/Microsoft/Recommenders/blob/master/notebooks/05_operationalize/als_movie_o16n.ipynb

**Comment by dennyac** [comment]
Thanks!!
