### ISSUE TITLE
Use jekyll as an alternative to host these Cosmic notes

### ISSUE THREAD

**Issue by dennyac** [AzureCosmosDB/CosmicNotes#2]
Hi @rimman, noticed that you just edit the html to add new content to Cosmic notes. 

Just wanted to know if you'd consider moving to Jekyll. I can help with that or raise a PR. Here's Cosmic Notes rendered with Jekyll (Just a prototype) - http://www.dennyac.com/jekyll-revealjs/#/

It should be easy to add new content with just markdown this way. GitHub Pages are powered by Jekyll behind the scenes, so they’re a great way to host your Jekyll-powered website for free.

**Comment by rimman** [comment]
I very much with intent decided to NOT use jekyll and keep the page "plain and simple".
Please feel free to copy and have a jekyll version in parallel.

thanks!

**Comment by dennyac** [comment]
Sounds reasonable!
